name: smart_campus
description: Smart Campus Mobile App

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  # НОВЫЕ ВЕРСИИ КАК В GO
  # Для работы с JWT токенами
  jwt_decoder: ^2.0.1
  shared_preferences: ^2.2.2
  # UI
  provider: ^6.1.1
  grpc: ^5.1.0
  protobuf: ^6.0.0
  protoc_plugin: ^25.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
